const cfg=window.PANTRYPAL_CONFIG;
const db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
let items=[],scanItems=[],selectedPhotoFile=null,editingId=null;
let groceryItems=JSON.parse(localStorage.getItem('pantrypal_grocery_items')||'[]');
let priceHistory=JSON.parse(localStorage.getItem('pantrypal_price_history')||'[]');
let activeDrawerItemId=null;

const starterPriceBook=[
 {normalized_name:'chicken breast',item_name:'Boneless Skinless Chicken Breast',store_name:'Walmart Pine City',date:'2026-06-28',amount:9.28,unit:'lb',total_price:23.02,unit_price:2.48,source:'Walmart cart screenshot'},
 {normalized_name:'chicken breast',item_name:'Boneless Skinless Chicken Breast',store_name:'ALDI Pine City',date:'2026-06-18',amount:6.00,unit:'lb',total_price:13.74,unit_price:2.29,source:'starter comparison target'},
 {normalized_name:'chicken breast',item_name:'Boneless Skinless Chicken Breast',store_name:'Walmart Pine City',date:'2026-05-21',amount:8.70,unit:'lb',total_price:24.27,unit_price:2.79,source:'starter comparison target'},
 {normalized_name:'ground beef',item_name:'80/20 Ground Beef Chuck',store_name:'Walmart Pine City',date:'2026-06-28',amount:5.00,unit:'lb',total_price:32.43,unit_price:6.49,source:'Walmart cart screenshot'},
 {normalized_name:'ground beef',item_name:'80/20 Ground Beef Chuck',store_name:'ALDI Pine City',date:'2026-06-20',amount:5.00,unit:'lb',total_price:27.45,unit_price:5.49,source:'starter comparison target'},
 {normalized_name:'ground beef',item_name:'80/20 Ground Beef Chuck',store_name:'ALDI Pine City',date:'2026-05-10',amount:5.00,unit:'lb',total_price:24.95,unit_price:4.99,source:'starter comparison target'},
 {normalized_name:'milk',item_name:'2% Milk Gallon',store_name:'Walmart Pine City',date:'2026-06-28',amount:1,unit:'gallon',total_price:3.92,unit_price:3.92,source:'Walmart cart screenshot'},
 {normalized_name:'eggs',item_name:'Large White Eggs 18 Count',store_name:'Walmart Pine City',date:'2026-06-28',amount:18,unit:'each',total_price:2.17,unit_price:.12,source:'Walmart cart screenshot'},
 {normalized_name:'cheese',item_name:'Colby & Monterey Jack Shredded Cheese',store_name:'Walmart Pine City',date:'2026-06-28',amount:32,unit:'oz',total_price:6.92,unit_price:.216,source:'Walmart cart screenshot'},
 {normalized_name:'bread',item_name:'Honey Wheat Bread',store_name:'Walmart Pine City',date:'2026-06-28',amount:2,unit:'loaf',total_price:6.96,unit_price:3.48,source:'Walmart cart screenshot'}
];
const defaultStapleTargets=[
 {name:'Ground Beef',target:10,unit:'lbs',aliases:['ground beef','beef']},
 {name:'Milk',target:2,unit:'gallon',aliases:['milk']},
 {name:'Eggs',target:36,unit:'each',aliases:['eggs','egg']},
 {name:'Bread',target:2,unit:'loaf',aliases:['bread']},
 {name:'Chicken',target:8,unit:'lbs',aliases:['chicken']},
 {name:'Cheese',target:2,unit:'lbs',aliases:['cheese']},
 {name:'Butter',target:4,unit:'sticks',aliases:['butter']},
 {name:'Pasta',target:4,unit:'box',aliases:['pasta','spaghetti','noodles']},
 {name:'Rice',target:5,unit:'lbs',aliases:['rice']},
 {name:'Tortillas',target:2,unit:'pack',aliases:['tortillas','tortilla']}
];
const preferredStores=['Walmart Pine City','Walmart Cambridge','ALDI Pine City','ALDI Cambridge','Target Cambridge','Coborn’s Pine City','Jerry’s Foods North Branch','Costco Coon Rapids','Costco Woodbury'];
const mockDeals={
 'Walmart Pine City':['Ground Beef family packs','Milk and eggs basics'],
 'Walmart Cambridge':['Pantry pasta rollback','Cheese and butter stock-up'],
 'ALDI Pine City':['Milk, eggs, bread value picks','Produce and pantry basics'],
 'ALDI Cambridge':['Bread, tortillas, rice value picks','Mild dinner staples'],
 'Target Cambridge':['Household add-ons','Drive-up grocery fill-ins'],
 'Coborn’s Pine City':['Local dairy preview','Fresh bakery bread'],
 'Jerry’s Foods North Branch':['Weekly meat and produce ad watch','Local grocery fill-in pricing'],
 'Costco Coon Rapids':['Bulk chicken and cheese','Rice and freezer staples'],
 'Costco Woodbury':['Bulk ground beef and butter','Family pantry cases']
};
const valueRules=[
 {keys:['ground beef','beef'],unit:'lbs',price:4.49},
 {keys:['chicken'],unit:'lbs',price:3.49},
 {keys:['pork'],unit:'lbs',price:3.29},
 {keys:['milk'],unit:'gallon',price:3.25},
 {keys:['eggs','egg'],unit:'each',price:.22},
 {keys:['bread'],unit:'loaf',price:2.75},
 {keys:['cheese'],unit:'lbs',price:4.99},
 {keys:['butter'],unit:'sticks',price:1.10},
 {keys:['pasta','spaghetti','noodles'],unit:'box',price:1.65},
 {keys:['rice'],unit:'lbs',price:1.10},
 {keys:['tortilla'],unit:'pack',price:2.50}
];
const $=id=>document.getElementById(id);
const categories=['Meat','Beef','Chicken','Pork','Fish/Seafood','Deli Meat','Dairy','Eggs','Produce','Bakery','Dry Goods','Canned Goods','Condiments','Snacks','Frozen','Beverages','Household','Other'];
const units=['item','each','count','lb','lbs','oz','g','kg','jar','can','box','bag','bottle','carton','package','pack','loaf','dozen','gallon','quart','pint','cup','tbsp','tsp','fl oz','stick','sticks'];
const locations=['Pantry','Kitchen Cupboard 1','Kitchen Cupboard 2','Kitchen Cupboard 3','Fridge','Freezer','Garage Freezer','Basement Fridge','Small Fridge','Small Freezer'];
const defaultPreferences={spiceLevel:'mild',dislikedIngredients:'spicy foods, hot sauce, jalapenos, cayenne-heavy recipes',favoriteMeals:'mild tacos, spaghetti, burgers, chicken rice, breakfast burritos, quesadillas',dietaryNotes:'simple, kid-friendly, mild meals with no spicy heat'};
const starterRecipes=[
 {name:'Mild Beef Tacos',time:'25 min',ingredients:['ground beef','tortillas','cheese','lettuce','tomato','mild taco seasoning'],uses:[['ground beef',1,'lbs'],['tortillas',6,'each']],steps:['Brown beef and drain.','Season with mild taco seasoning.','Serve with tortillas, cheese, and mild toppings.']},
 {name:'Simple Spaghetti',time:'30 min',ingredients:['pasta','spaghetti sauce','ground beef','parmesan'],uses:[['pasta',1,'box'],['ground beef',1,'lbs']],steps:['Boil pasta.','Warm sauce and cooked beef.','Combine and serve with cheese.']},
 {name:'Mild Chili',time:'45 min',ingredients:['ground beef','beans','tomato sauce','mild chili seasoning','cheese'],uses:[['ground beef',1,'lbs'],['beans',1,'can']],steps:['Brown beef.','Add beans, tomato sauce, and mild seasoning.','Simmer and serve with cheese.']},
 {name:'Breakfast Burritos',time:'20 min',ingredients:['eggs','tortillas','cheese','breakfast sausage'],uses:[['eggs',6,'each'],['tortillas',6,'each']],steps:['Scramble eggs.','Add cheese and cooked meat if available.','Wrap in tortillas.']},
 {name:'Chicken Fried Rice',time:'25 min',ingredients:['chicken','rice','eggs','mixed vegetables','soy sauce'],uses:[['chicken',1,'lbs'],['rice',2,'cup']],steps:['Cook chicken.','Stir fry rice, egg, and vegetables.','Add mild seasoning or soy sauce.']},
 {name:'Cheese Quesadillas',time:'15 min',ingredients:['tortillas','cheese','chicken'],uses:[['tortillas',4,'each'],['cheese',1,'cup']],steps:['Add cheese to tortillas.','Add chicken if available.','Toast until melted.']}
];
init();
function init(){
 fillSelect('category',categories,'Dry Goods');fillSelect('unit',units,'item');fillSelect('location',locations,'Pantry');fillSelect('scanLocation',locations,'Pantry');
 wireTabs();loadPreferences();
 $('itemForm').addEventListener('submit',addManual);
 $('scanMode').addEventListener('change',updateScanHint);
 $('takePhotoBtn').addEventListener('click',()=>$('cameraInput').click());$('uploadPhotoBtn').addEventListener('click',()=>$('uploadInput').click());
 $('cameraInput').addEventListener('change',previewPhoto);$('uploadInput').addEventListener('change',previewPhoto);
 $('scanBtn').addEventListener('click',scanPhoto);$('saveScanBtn').addEventListener('click',saveScan);
 $('search').addEventListener('input',render);$('recipeBtn').addEventListener('click',getRecipeIdeas);$('starterRecipeBtn').addEventListener('click',renderStarterRecipes);
 $('savePreferencesBtn').addEventListener('click',savePreferences);$('manualGroceryBtn').addEventListener('click',addManualGrocery);$('resetStaplesBtn').addEventListener('click',resetStapleTargets);if($('savePriceRecordBtn'))$('savePriceRecordBtn').addEventListener('click',savePriceRecord);
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closeItemDrawer()});updateScanHint();renderStapleTargetEditor();load();showTab('home');
}
function wireTabs(){document.querySelectorAll('.tab-button').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)))}
function showTab(tab){document.querySelectorAll('.tab-button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===tab))}
function getPreferences(){return JSON.parse(localStorage.getItem('pantrypal_preferences')||JSON.stringify(defaultPreferences))}
function loadPreferences(){const p=getPreferences();$('spiceLevel').value=p.spiceLevel||'mild';$('dislikedIngredients').value=p.dislikedIngredients||defaultPreferences.dislikedIngredients;$('favoriteMeals').value=p.favoriteMeals||defaultPreferences.favoriteMeals;$('dietaryNotes').value=p.dietaryNotes||defaultPreferences.dietaryNotes}
function savePreferences(){const p={spiceLevel:$('spiceLevel').value,dislikedIngredients:$('dislikedIngredients').value,favoriteMeals:$('favoriteMeals').value,dietaryNotes:$('dietaryNotes').value};localStorage.setItem('pantrypal_preferences',JSON.stringify(p));$('preferenceStatus').textContent='Preferences saved.';renderStarterRecipes()}
function updateScanHint(){const mode=$('scanMode').value;$('scanHint').textContent=mode==='meat_label'?'Meat label mode: take one close photo of the store label.':'General mode: scan pantry, fridge, freezer, or package fronts.'}
async function load(){
 $('status').textContent='Loading...';const {data,error}=await db.from('pantry_items').select('*').order('created_at',{ascending:false});
 if(error){$('status').textContent='Database error: '+error.message;return}
 items=data||[];$('status').textContent='Connected · '+items.length+' item(s)';$('inventoryCount').textContent=items.length+' item'+(items.length===1?'':'s');render();renderStarterRecipes();
}
function readForm(){return{name:$('name').value.trim(),category:$('category').value,location:$('location').value,quantity:+$('quantity').value||1,unit:$('unit').value||'item',best_by:$('bestBy').value||null,notes:$('notes').value||'',low_stock:$('lowStock').checked}}
async function addManual(e){e.preventDefault();await insert([readForm()]);e.target.reset();$('quantity').value=1;$('unit').value='item';$('category').value='Dry Goods';$('location').value='Pantry';await load()}
async function insert(rows){const {error}=await db.from('pantry_items').insert(rows);if(error){alert(error.message);throw error}}
function render(){renderInventory();renderGroceryList();renderHome()}
function renderInventory(){const q=$('search').value.toLowerCase();const list=items.filter(i=>!q||(i.name||'').toLowerCase().includes(q)||(i.location||'').toLowerCase().includes(q)||(i.category||'').toLowerCase().includes(q)||(i.unit||'').toLowerCase().includes(q)||(i.notes||'').toLowerCase().includes(q));$('inventory').innerHTML=list.length?list.map(i=>editingId===i.id?editCard(i):itemCard(i)).join(''):'<p>No matching items.</p>'}
function itemCard(i){const intel=itemPriceIntel(i);const unitLine=intel.records.length?'<div class="item-intel-row"><span>Last '+money2(intel.last.unit_price)+'/'+esc(intel.basis)+'</span><span>Avg '+money2(intel.avg)+'/'+esc(intel.basis)+'</span><span>'+esc(intel.bestStore)+'</span></div>':'<div class="item-intel-row"><span>No price history yet</span><span>Click to add receipt price</span></div>';return '<div class="item intel-item" onclick="openItemDrawer(\''+i.id+'\')" role="button" tabindex="0"><div class="item-head"><div><h3>'+esc(i.name)+'</h3><p>'+esc(i.quantity)+' '+esc(i.unit)+' · '+esc(i.location)+' · '+esc(i.category)+'</p></div>'+(i.low_stock?'<span class="pill">Low stock</span>':'<span class="pill soft-pill">Details</span>')+'</div>'+unitLine+(i.best_by?'<p class="meta">Best by: '+esc(i.best_by)+'</p>':'')+(i.notes?'<p class="notes">'+esc(i.notes)+'</p>':'')+'<div class="button-row"><button onclick="event.stopPropagation();useAmountPrompt(\''+i.id+'\')">Use Amount</button><button class="secondary" onclick="event.stopPropagation();useAll(\''+i.id+'\')">Use All</button><button onclick="event.stopPropagation();startEdit(\''+i.id+'\')">Edit</button><button class="secondary" onclick="event.stopPropagation();toggleLow(\''+i.id+'\','+(!i.low_stock)+')">'+(i.low_stock?'Remove from List':'Add to List')+'</button><button class="danger" onclick="event.stopPropagation();del(\''+i.id+'\')">Delete</button></div></div>'}
function editCard(i){return '<div class="item edit-card"><h3>Edit Item</h3><input id="edit-name-'+i.id+'" value="'+esc(i.name)+'"><div class="grid"><select id="edit-category-'+i.id+'">'+options(categories,i.category)+'</select><select id="edit-location-'+i.id+'">'+options(locations,i.location)+'</select><input id="edit-quantity-'+i.id+'" type="number" step="0.25" value="'+esc(i.quantity)+'"><select id="edit-unit-'+i.id+'">'+options(units,i.unit)+'</select></div><input id="edit-best-'+i.id+'" type="date" value="'+esc(i.best_by||'')+'"><textarea id="edit-notes-'+i.id+'">'+esc(i.notes||'')+'</textarea><label class="checkrow"><input id="edit-low-'+i.id+'" type="checkbox" '+(i.low_stock?'checked':'')+'> Low stock / add to grocery list</label><div class="button-row two-actions"><button onclick="saveEdit(\''+i.id+'\')">Save Changes</button><button class="secondary" onclick="cancelEdit()">Cancel</button></div></div>'}
function renderGroceryList(){const low=items.filter(i=>i.low_stock).map(i=>({name:i.name,detail:i.quantity+' '+i.unit+' · '+i.location,source:'inventory',id:i.id}));const targetLow=stapleStats().filter(s=>s.level==='Low').map(s=>({name:s.name,detail:'Target gap: '+fmt(Math.max(s.target-s.current,0))+' '+s.unit,source:'target'}));const all=[...low,...targetLow,...groceryItems];const list=all.length?all.map((i,idx)=>'<div class="grocery-item"><strong>'+esc(i.name)+'</strong><span>'+esc(i.detail||'')+'</span>'+(i.source==='inventory'?'<button class="secondary small" onclick="toggleLow(\''+i.id+'\',false)">Got it</button>':i.source==='target'?'<button class="secondary small" onclick="addManualGroceryNamed(\''+escAttr(i.name)+'\')">Plan</button>':'<button class="secondary small" onclick="clearManualGrocery('+(idx-low.length-targetLow.length)+')">Remove</button>')+'</div>').join(''):"<p class='muted'>No grocery items yet.</p>";$('groceryList').innerHTML=list+shoppingPlanPreview(all)}
function getStapleTargets(){return JSON.parse(localStorage.getItem('pantrypal_staple_targets')||JSON.stringify(defaultStapleTargets))}
function saveStapleTargets(t){localStorage.setItem('pantrypal_staple_targets',JSON.stringify(t));renderStapleTargetEditor();renderHome()}
function resetStapleTargets(){saveStapleTargets(defaultStapleTargets);$('pantryScoreSummary').textContent='Staple targets reset to the Rush City starter list.'}
function stapleAmount(target){return items.reduce((sum,i)=>{const hay=String(i.name||'').toLowerCase();const match=(target.aliases||[target.name]).some(a=>hay.includes(String(a).toLowerCase()));return match?sum+convertQty(Number(i.quantity)||0,i.unit,target.unit):sum},0)}
function convertQty(q,from,to){const f=String(from||'').toLowerCase(),t=String(to||'').toLowerCase();if(t==='lbs'&&['lb','lbs','pound','pounds'].includes(f))return q;if(t==='gallon'&&['gallon','gallons'].includes(f))return q;if(t==='each'&&['each','count','item','dozen'].includes(f))return f==='dozen'?q*12:q;if(t==='loaf'&&['loaf','loaves'].includes(f))return q;if(t==='sticks'&&['stick','sticks'].includes(f))return q;if(t==='box'&&['box','boxes'].includes(f))return q;if(t==='pack'&&['pack','package'].includes(f))return q;return q}
function stapleLevel(ratio){if(ratio<.35)return'Low';if(ratio<.75)return'Medium';return'High'}
function stapleStats(){return getStapleTargets().map(t=>{const current=stapleAmount(t);const ratio=t.target?Math.min(current/t.target,1):0;return{...t,current,ratio,level:stapleLevel(ratio)}})}
function pantryScore(stats=stapleStats()){return stats.length?Math.round(stats.reduce((n,s)=>n+s.ratio,0)/stats.length*100):0}
function setTextIfPresent(id,value){const el=$(id);if(el)el.textContent=value}
function renderHome(){
 const stats=stapleStats();
 const score=pantryScore(stats);
 const low=stats.filter(s=>s.level==='Low');
 document.documentElement.style.setProperty('--score',score);
 setTextIfPresent('pantryScore',score);
 setTextIfPresent('pantryScorePill',score+'%');
 setTextIfPresent('pantryScoreSummary',score>=80?'Cabin shelves look strong.':score>=50?'Good start — a few staples need a store run.':'Low staple coverage — build a quick shopping plan.');
 setTextIfPresent('homeInventoryStat',items.length+' item'+(items.length===1?'':'s'));
 setTextIfPresent('homeLowStat',low.length+' low');
 const staplesEl=$('staplesGlance');
 if(staplesEl)staplesEl.innerHTML=stats.map(s=>'<div class="staple-card"><div class="item-head"><h3>'+esc(s.name)+'</h3><strong class="level-'+s.level.toLowerCase()+'">'+s.level+'</strong></div><p>'+fmt(s.current)+' / '+fmt(s.target)+' '+esc(s.unit)+'</p><div class="staple-meter" style="--pct:'+Math.round(s.ratio*100)+'%"><span></span></div></div>').join('');
 const criticalEl=$('criticalStaples');
 if(criticalEl)criticalEl.innerHTML=low.length?low.map(s=>'<div class="grocery-item"><strong>'+esc(s.name)+'</strong><span>Need about '+fmt(Math.max(s.target-s.current,0))+' '+esc(s.unit)+' to hit target.</span><button class="small" onclick="addManualGroceryNamed(\''+escAttr(s.name)+'\')">Add</button></div>').join(''):'<p class="muted">No critical low staples right now.</p>';
 renderPantryHealth(stats);renderPantryValue();renderTonightDinner(stats);renderStoreDeals(low)
}
function renderPantryHealth(stats){const groups=[{name:'Protein',score:categoryScore(['Meat','Beef','Chicken','Pork','Fish/Seafood','Deli Meat'])},{name:'Dairy',score:categoryScore(['Dairy','Eggs'])},{name:'Produce',score:categoryScore(['Produce'])},{name:'Frozen',score:locationScore(['Freezer','Garage Freezer','Small Freezer'])},{name:'Staples',score:pantryScore(stats)}];$('pantryHealth').innerHTML=groups.map(g=>'<div class="health-row"><strong>'+esc(g.name)+'</strong><span>'+g.score+'%</span><div class="health-meter" style="--pct:'+g.score+'%"><span></span></div></div>').join('')}
function categoryScore(cats){const count=items.filter(i=>cats.includes(i.category)).length;return Math.max(0,Math.min(100,Math.round(count/4*100)))}
function locationScore(locs){const count=items.filter(i=>locs.includes(i.location)).length;return Math.max(0,Math.min(100,Math.round(count/5*100)))}
function renderPantryValue(){
 const totals=items.reduce((acc,i)=>{const loc=i.location||'Pantry';const bucket=loc.toLowerCase().includes('freezer')?'Freezer':loc.toLowerCase().includes('fridge')?'Fridge':'Pantry';acc[bucket]=(acc[bucket]||0)+estimateItemValue(i);return acc},{Pantry:0,Fridge:0,Freezer:0});
 const total=Object.values(totals).reduce((a,b)=>a+b,0);
 const meals=Math.max(0,Math.round(total/6));
 setTextIfPresent('homeValueStat',money(total));
 setTextIfPresent('homeMealsStat',meals+' meals');
 const el=$('pantryValue');
 if(el)el.innerHTML='<div class="value-row"><span>Total estimated value</span><strong class="value-total">'+money(total)+'</strong></div>'+['Pantry','Fridge','Freezer'].map(k=>'<div class="value-row"><span>'+k+'</span><strong>'+money(totals[k]||0)+'</strong></div>').join('')+'<p class="muted">Estimated meals available: <strong>'+meals+'</strong>. Values are rough planning estimates, not live prices.</p>'
}
function estimateItemValue(item){const name=String(item.name||'').toLowerCase();const rule=valueRules.find(r=>r.keys.some(k=>name.includes(k)));if(rule)return convertQty(Number(item.quantity)||0,item.unit,rule.unit)*rule.price;const qty=Number(item.quantity)||1;if(item.category==='Meat'||item.category==='Beef'||item.category==='Chicken'||item.category==='Pork')return qty*4;if(item.category==='Produce')return qty*2.5;if(item.category==='Dairy'||item.category==='Eggs')return qty*3;if(item.location&&String(item.location).toLowerCase().includes('freezer'))return qty*4;return qty*2}
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}
function renderTonightDinner(stats){const pick=starterRecipes.map((r,idx)=>({r,idx,have:r.ingredients.filter(x=>findInventoryMatch(x)).length})).sort((a,b)=>b.have-a.have)[0];$('tonightDinner').innerHTML=pick?'<div class="recipe"><div class="item-head"><h3>'+esc(pick.r.name)+'</h3><span class="pill">Mild</span></div><p>Best built-in match from your pantry right now. Uses '+pick.have+' ingredient match(es).</p><button onclick="showTab(\'recipes\')">Open Recipes</button></div>':'<p class="muted">Add pantry items to get a dinner idea.</p>'}
function renderStoreDeals(low){
 const needs=(low.length?low:stapleStats().filter(s=>s.level!=='High')).slice(0,4).map(s=>s.name);
 const storeRows=[
  {name:'Jerry’s Foods North Branch',note:'Local fill-in stop',save:'Watch ad',badge:'Near option'},
  {name:'ALDI Pine City',note:'Milk, eggs, bread, produce basics',save:'Value stop',badge:'Good basics'},
  {name:'Walmart Pine City',note:'Base grocery stop for pantry gaps',save:'Start here',badge:'Main stop'}
 ];
 const el=$('storeDealsPreview');
 if(el)el.innerHTML=storeRows.map((s,idx)=>'<div class="store-row"><div class="store-logo">'+esc(s.name.split(' ')[0].slice(0,1))+'</div><div><h3>'+esc(s.name)+'</h3><p>'+esc(s.note)+' · Plan: '+esc(needs.length?needs.join(', '):'weekly ad check')+'</p></div><strong class="store-save">'+esc(s.save)+'</strong><span class="store-badge">'+esc(s.badge)+'</span></div>').join('')
}
function renderStapleTargetEditor(){const targets=getStapleTargets();$('stapleTargetEditor').innerHTML=targets.map((t,i)=>'<div class="target-row"><input id="target-name-'+i+'" value="'+esc(t.name)+'"><input id="target-qty-'+i+'" type="number" step="0.25" value="'+esc(t.target)+'"><input id="target-unit-'+i+'" value="'+esc(t.unit)+'"><button class="small secondary" onclick="saveTargetRow('+i+')">Save</button></div>').join('')}
function saveTargetRow(i){const targets=getStapleTargets();targets[i]={...targets[i],name:$('target-name-'+i).value.trim(),target:+$('target-qty-'+i).value||1,unit:$('target-unit-'+i).value.trim()||'item',aliases:[$('target-name-'+i).value.trim().toLowerCase()]};saveStapleTargets(targets)}
function shoppingPlanPreview(all){const names=all.map(i=>i.name).slice(0,6);const focus=names.length?names.join(', '):'weekly ad check';return '<div class="compact-card trip-card"><p class="eyebrow">Shopping Recommendation</p><h3>Trip Value Placeholder</h3><p class="muted">Future live pricing will compare savings, fuel, drive time, and bulk value before recommending extra stops.</p><div class="trip-value"><div><span>Est. savings</span><strong>Pending</strong></div><div><span>Extra miles</span><strong>Pending</strong></div><div><span>Worth trip?</span><strong>Needs prices</strong></div></div><p><strong>Plan focus:</strong> '+esc(focus)+'</p></div><div class="compact-card"><p class="eyebrow">Shopping Plan Preview</p><h3>Preferred Stores</h3>'+preferredStores.map((s,idx)=>'<div class="grocery-item"><strong>'+esc(s)+'</strong><span>Mock slot '+(idx+1)+': '+esc(names[idx%Math.max(names.length,1)]||'weekly ad check')+' · ready for future ad, price-history, and trip-value data.</span></div>').join('')+'</div>'}
function addManualGroceryNamed(name){if(!groceryItems.some(i=>i.name.toLowerCase()===String(name).toLowerCase()))groceryItems.push({name,detail:'Low staple target'});localStorage.setItem('pantrypal_grocery_items',JSON.stringify(groceryItems));renderGroceryList();showTab('grocery')}

function normalizePriceName(name){const s=String(name||'').toLowerCase();if(s.includes('chicken breast')||s.includes('boneless')&&s.includes('chicken'))return'chicken breast';if(s.includes('ground beef')||s.includes('hamburger')||s.includes('80/20'))return'ground beef';if(s.includes('milk'))return'milk';if(s.includes('egg'))return'eggs';if(s.includes('cheese'))return'cheese';if(s.includes('bread'))return'bread';if(s.includes('pasta')||s.includes('spaghetti')||s.includes('fettuccine'))return'pasta';if(s.includes('corn'))return'corn';if(s.includes('pea'))return'peas';return s.split(',')[0].replace(/great value|freshness guaranteed|fresh|reduced fat|whole|golden sweet|large white/gi,'').trim()||s.trim()}
function priceBasisFor(name,unit){const n=normalizePriceName(name);if(n.includes('chicken')||n.includes('beef'))return'lb';if(n==='milk')return'gallon';if(n==='eggs')return'each';if(n==='cheese')return'oz';if(String(unit||'').toLowerCase().includes('lb'))return'lb';return String(unit||'each').toLowerCase()}
function allPriceRecords(){return [...starterPriceBook,...priceHistory].filter(r=>r&&r.normalized_name)}
function recordsForItem(item){const key=normalizePriceName(item.name);return allPriceRecords().filter(r=>r.normalized_name===key).sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
function itemPriceIntel(item){const records=recordsForItem(item);const basis=records[0]?.unit||priceBasisFor(item.name,item.unit);if(!records.length)return{records:[],basis,last:null,avg:0,low:0,high:0,bestStore:'Price history'};const prices=records.map(r=>Number(r.unit_price)||0).filter(n=>n>0);const avg=prices.reduce((a,b)=>a+b,0)/prices.length;const low=Math.min(...prices),high=Math.max(...prices);const best=records.filter(r=>Number(r.unit_price)===low)[0];return{records,basis,last:records[0],avg,low,high,bestStore:best?best.store_name:'Price history'}}
function money2(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function todayISO(){return new Date().toISOString().slice(0,10)}
function openItemDrawer(id){const item=items.find(i=>String(i.id)===String(id));if(!item)return;activeDrawerItemId=id;const key=normalizePriceName(item.name);const related=items.filter(i=>normalizePriceName(i.name)===key);const totalQty=related.reduce((sum,i)=>sum+(Number(i.quantity)||0),0);const intel=itemPriceIntel(item);$('drawerItemName').textContent=item.name;$('drawerItemSub').textContent=item.category+' · '+item.location+' · '+fmt(item.quantity)+' '+item.unit;$('drawerCurrentStock').innerHTML='<div class="stock-big"><strong>'+fmt(totalQty)+'</strong><span>'+esc(item.unit||intel.basis)+' total</span></div>'+related.map(i=>'<div class="stock-row"><span>'+esc(i.location)+'</span><strong>'+fmt(i.quantity)+' '+esc(i.unit)+'</strong></div>').join('');$('drawerBuyVerdict').innerHTML=buyVerdictHtml(item,intel);$('drawerChartTitle').textContent=(normalizePriceName(item.name).replace(/\b\w/g,c=>c.toUpperCase()))+' price trend';$('drawerPriceBasis').textContent=intel.basis?('$/'+intel.basis):'price book';$('drawerPriceChart').innerHTML=priceChartSvg(intel.records);$('drawerStoreCompare').innerHTML=storeCompareHtml(intel.records);$('drawerPurchaseLog').innerHTML=purchaseLogHtml(intel.records);$('priceDate').value=todayISO();$('priceUnit').value=intel.basis==='lb'?'lb':intel.basis==='gallon'?'gallon':intel.basis==='oz'?'oz':'each';$('priceTotal').value='';$('priceAmount').value='';$('itemDrawer').classList.add('open');$('itemDrawerBackdrop').classList.remove('hidden');document.body.classList.add('drawer-open')}
function closeItemDrawer(){if($('itemDrawer')){$('itemDrawer').classList.remove('open');$('itemDrawer').setAttribute('aria-hidden','true')}if($('itemDrawerBackdrop'))$('itemDrawerBackdrop').classList.add('hidden');document.body.classList.remove('drawer-open');activeDrawerItemId=null}
function buyVerdictHtml(item,intel){if(!intel.records.length)return'<h3>Start tracking this item.</h3><p class="muted">Add receipt prices here. PantryPal will learn your normal price and flag good stock-up buys.</p>';const target=targetBuyPrice(normalizePriceName(item.name),intel.avg,intel.low);const last=intel.last;const quality=Number(last.unit_price)<=target.stock?'Stock-up price':Number(last.unit_price)<=target.buy?'Good buy':'Only buy if needed';return'<h3>'+esc(quality)+'</h3><p>Last seen at <strong>'+esc(last.store_name)+'</strong> for <strong>'+money2(last.unit_price)+'/'+esc(intel.basis)+'</strong>.</p><div class="verdict-metrics"><span>Buy under <strong>'+money2(target.buy)+'</strong></span><span>Stock up under <strong>'+money2(target.stock)+'</strong></span><span>Average <strong>'+money2(intel.avg)+'</strong></span></div>'}
function targetBuyPrice(key,avg,low){if(key==='chicken breast')return{buy:2.35,stock:2.15};if(key==='ground beef')return{buy:5.74,stock:5.25};return{buy:avg*.95||low,stock:avg*.88||low}}
function priceChartSvg(records){const rs=(records||[]).slice().reverse().filter(r=>Number(r.unit_price)>0).slice(-8);if(!rs.length)return'<div class="empty-chart">No price records yet.</div>';const prices=rs.map(r=>Number(r.unit_price));const min=Math.min(...prices),max=Math.max(...prices);const span=max-min||1;const pts=prices.map((p,i)=>{const x=20+i*(260/Math.max(rs.length-1,1));const y=116-((p-min)/span*82);return{x,y,p,r:rs[i]}});const poly=pts.map(p=>p.x+','+p.y).join(' ');return'<svg viewBox="0 0 300 138" role="img" aria-label="Price history chart"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#7ea05d" stop-opacity=".38"/><stop offset="1" stop-color="#7ea05d" stop-opacity="0"/></linearGradient></defs><path d="M20 124 L'+poly.replaceAll(' ',' L')+' L280 124 Z" fill="url(#chartFill)"/><polyline points="'+poly+'" fill="none" stroke="#2f6543" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>'+pts.map(p=>'<circle cx="'+p.x+'" cy="'+p.y+'" r="5" fill="#fff8e8" stroke="#2f6543" stroke-width="3"/>').join('')+'<text x="20" y="18" fill="#5f523b" font-size="11" font-weight="800">Low '+money2(min)+'</text><text x="205" y="18" fill="#5f523b" font-size="11" font-weight="800">High '+money2(max)+'</text></svg>'}
function storeCompareHtml(records){if(!records.length)return'<p class="muted">No store data yet.</p>';const grouped={};records.forEach(r=>{(grouped[r.store_name] ||= []).push(r)});return Object.entries(grouped).map(([store,rs])=>{const prices=rs.map(r=>Number(r.unit_price)).filter(n=>n>0);const avg=prices.reduce((a,b)=>a+b,0)/prices.length;const low=Math.min(...prices);const last=rs.sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0];return'<div class="store-compare-row"><div><strong>'+esc(store)+'</strong><span>Last '+money2(last.unit_price)+' · Low '+money2(low)+'</span></div><b>Avg '+money2(avg)+'</b></div>'}).join('')}
function purchaseLogHtml(records){if(!records.length)return'<p class="muted">No purchase records yet. Add the next receipt price here.</p>';return records.slice(0,10).map(r=>'<div class="purchase-row"><div><strong>'+esc(r.date||'No date')+' · '+esc(r.store_name)+'</strong><span>'+esc(r.item_name||'Purchase')+' · '+fmt(r.amount)+' '+esc(r.unit)+'</span></div><b>'+money2(r.unit_price)+'/'+esc(r.unit)+'</b></div>').join('')}
function savePriceRecord(){const item=items.find(i=>String(i.id)===String(activeDrawerItemId));if(!item)return;const total=Number($('priceTotal').value);const amount=Number($('priceAmount').value);if(!total||!amount||total<=0||amount<=0){alert('Enter a total price and amount.');return}const unit=$('priceUnit').value;const rec={normalized_name:normalizePriceName(item.name),item_name:item.name,store_name:$('priceStore').value,date:$('priceDate').value||todayISO(),amount,unit,total_price:total,unit_price:total/amount,source:'manual receipt entry'};priceHistory.push(rec);localStorage.setItem('pantrypal_price_history',JSON.stringify(priceHistory));openItemDrawer(item.id);renderInventory()}

function fmt(n){return Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}
function escAttr(v){return String(v??'').replaceAll('\\','\\\\').replaceAll("'","\\'")}
function startEdit(id){editingId=id;renderInventory()}function cancelEdit(){editingId=null;renderInventory()}
async function saveEdit(id){const row={name:$('edit-name-'+id).value.trim(),category:$('edit-category-'+id).value,location:$('edit-location-'+id).value,quantity:+$('edit-quantity-'+id).value||1,unit:$('edit-unit-'+id).value||'item',best_by:$('edit-best-'+id).value||null,notes:$('edit-notes-'+id).value||'',low_stock:$('edit-low-'+id).checked};const {error}=await db.from('pantry_items').update(row).eq('id',id);if(error){alert(error.message);return}editingId=null;await load()}
async function useAmountPrompt(id){const item=items.find(i=>i.id===id);if(!item)return;const current=Number(item.quantity);if(!Number.isFinite(current)){startEdit(id);return}const raw=prompt('How much '+item.unit+' did you use?','1');if(raw===null)return;const used=Number(raw);if(!Number.isFinite(used)||used<=0){alert('Enter a number greater than 0.');return}await subtractItem(item,used)}
async function useAll(id){const item=items.find(i=>i.id===id);if(item&&confirm('Use all of '+item.name+'?'))await del(id,true)}
async function subtractItem(item,used){const remaining=Number(item.quantity)-used;if(remaining<=0){await del(item.id,true);return}const {error}=await db.from('pantry_items').update({quantity:remaining}).eq('id',item.id);if(error){alert(error.message);return}await load()}
async function toggleLow(id,val){const {error}=await db.from('pantry_items').update({low_stock:val}).eq('id',id);if(error){alert(error.message);return}await load()}
async function del(id,skip=false){if(!skip&&!confirm('Delete this item from PantryPal?'))return;await db.from('pantry_items').delete().eq('id',id);await load()}
function addManualGrocery(){const name=$('manualGroceryName').value.trim();if(!name)return;groceryItems.push({name,detail:'Manual item'});localStorage.setItem('pantrypal_grocery_items',JSON.stringify(groceryItems));$('manualGroceryName').value='';renderGroceryList()}
function clearManualGrocery(idx){groceryItems.splice(idx,1);localStorage.setItem('pantrypal_grocery_items',JSON.stringify(groceryItems));renderGroceryList()}
function addMissingToGrocery(names){names.forEach(name=>{if(name&&!groceryItems.some(i=>i.name.toLowerCase()===String(name).toLowerCase()))groceryItems.push({name,detail:'Missing recipe ingredient'})});localStorage.setItem('pantrypal_grocery_items',JSON.stringify(groceryItems));renderGroceryList();showTab('grocery')}
async function markCooked(idx){const recipe=starterRecipes[idx];if(!recipe)return;for(const u of recipe.uses){const item=findInventoryMatch(u[0]);if(item)await subtractItem(item,Number(u[1])||1)}await load()}
function findInventoryMatch(name){const key=String(name).toLowerCase();return items.find(i=>String(i.name).toLowerCase().includes(key)||key.includes(String(i.name).toLowerCase()))}
function previewPhoto(e){const f=e.target.files[0];if(!f)return;selectedPhotoFile=f;scanItems=[];$('scanResults').innerHTML='';$('saveScanBtn').classList.add('hidden');$('preview').src=URL.createObjectURL(f);$('preview').classList.remove('hidden');$('scanStatus').textContent='Photo selected: '+(f.name||'camera photo')}
async function scanPhoto(){const f=selectedPhotoFile;if(!f){$('scanStatus').textContent='Choose or take a photo first.';return}try{const imageBase64=await imageToJpegBase64(f,1280,0.82);const r=await fetch('/scan-pantry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageBase64,mimeType:'image/jpeg',location:$('scanLocation').value,scanMode:$('scanMode').value})});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{throw new Error(raw.slice(0,160)||'Server error')}if(!r.ok)throw new Error(data.error||'Scan failed');scanItems=(data.items||[]).map(x=>({name:x.name||'',category:normalizeCategory(x.category),location:x.location||$('scanLocation').value,quantity:Number(x.quantity)||1,unit:normalizeUnit(x.unit),best_by:x.expiration_date||x.best_by||null,notes:x.confidence?'AI confidence: '+x.confidence:'',low_stock:false}));renderScan();$('scanStatus').textContent='Found '+scanItems.length+' item(s).'}catch(e){$('scanStatus').textContent='Scan error: '+e.message}}
function renderScan(){$('scanResults').innerHTML=scanItems.map((i,n)=>'<div class="scan-card" data-i="'+n+'"><label class="checkrow"><input class="save" type="checkbox" checked> Save</label><input class="n" value="'+esc(i.name)+'"><div class="grid"><select class="c">'+options(categories,i.category)+'</select><select class="l">'+options(locations,i.location)+'</select><input class="q" type="number" step="0.01" value="'+esc(i.quantity)+'"><select class="u">'+options(units,i.unit)+'</select></div><input class="b" type="date" value="'+esc(i.best_by||'')+'"><textarea class="notes-input">'+esc(i.notes||'')+'</textarea><label class="checkrow"><input class="low" type="checkbox"> Low stock</label></div>').join('');$('saveScanBtn').classList.remove('hidden')}
async function saveScan(){const rows=[...document.querySelectorAll('.scan-card')].filter(c=>c.querySelector('.save').checked).map(c=>({name:c.querySelector('.n').value.trim(),category:c.querySelector('.c').value,quantity:+c.querySelector('.q').value||1,unit:c.querySelector('.u').value||'item',location:c.querySelector('.l').value,best_by:c.querySelector('.b').value||null,notes:c.querySelector('.notes-input').value||'',low_stock:c.querySelector('.low').checked})).filter(r=>r.name);if(!rows.length){$('scanStatus').textContent='No checked items to save.';return}await insert(rows);$('scanResults').innerHTML='';$('saveScanBtn').classList.add('hidden');await load()}
async function getRecipeIdeas(){if(!items.length){$('recipeStatus').textContent='Add or scan some inventory first.';return}$('recipeStatus').textContent='Building mild ideas...';try{const inventory=items.slice(0,80).map(i=>({name:i.name,category:i.category,location:i.location,quantity:i.quantity,unit:i.unit,best_by:i.best_by,notes:i.notes}));const r=await fetch('/recipe-ideas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inventory,style:$('recipeStyle').value,preferences:getPreferences()})});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{throw new Error(raw.slice(0,160)||'Server error')}if(!r.ok)throw new Error(data.error||'Recipe failed');renderAiRecipes(data.recipes||[]);$('recipeStatus').textContent='Found '+(data.recipes||[]).length+' mild idea(s).'}catch(e){$('recipeStatus').textContent='Recipe error: '+e.message}}
function renderStarterRecipes(){const recipes=starterRecipes.map(r=>{const have=[],missing=[];r.ingredients.forEach(x=>findInventoryMatch(x)?have.push(x):missing.push(x));return {...r,have,missing}});$('recipeIdeas').innerHTML=recipes.map((r,idx)=>'<div class="recipe"><div class="item-head"><h3>'+esc(r.name)+'</h3><span class="pill">'+esc(r.time)+'</span></div><p><strong>Have:</strong> '+(r.have.length?r.have.map(esc).join(', '):'None found yet')+'</p><p><strong>Missing:</strong> '+(r.missing.length?r.missing.map(esc).join(', '):'Nothing obvious')+'</p><ol>'+r.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol><div class="button-row two-actions"><button onclick="addMissingToGrocery(starterRecipes['+idx+'].ingredients.filter(x=>!findInventoryMatch(x)))">Add Missing</button><button class="secondary" onclick="markCooked('+idx+')">Cook This</button></div></div>').join('');$('recipeStatus').textContent='Built-in recipes are mild starter templates. No recipe websites are scraped.'}
function renderAiRecipes(recipes){$('recipeIdeas').innerHTML=recipes.length?recipes.map(r=>'<div class="recipe"><div class="item-head"><h3>'+esc(r.name)+'</h3><span class="pill">'+esc(r.time||'Quick')+'</span></div><p>'+esc(r.why||'')+'</p><p><strong>Use:</strong> '+(r.use||[]).map(esc).join(', ')+'</p><p><strong>Missing:</strong> '+((r.missing||[]).length?r.missing.map(esc).join(', '):'Nothing obvious')+'</p><ol>'+(r.steps||[]).map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol></div>').join(''):'<p>No recipe ideas came back.</p>'}
function imageToJpegBase64(file,maxSize=1280,quality=0.78){return new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{try{let w=img.width,h=img.height;const scale=Math.min(1,maxSize/Math.max(w,h));w=Math.round(w*scale);h=Math.round(h*scale);const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',quality).split(',')[1])}catch(e){URL.revokeObjectURL(url);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Could not read image'))};img.src=url})}
function normalizeCategory(v){const s=String(v||'').toLowerCase();if(s.includes('beef'))return'Beef';if(s.includes('chicken'))return'Chicken';if(s.includes('pork'))return'Pork';if(s.includes('fish')||s.includes('seafood'))return'Fish/Seafood';if(s.includes('meat'))return'Meat';if(s.includes('egg'))return'Eggs';if(s.includes('dairy'))return'Dairy';if(s.includes('produce'))return'Produce';if(s.includes('frozen'))return'Frozen';return categories.find(c=>c.toLowerCase()===s)||'Other'}
function normalizeUnit(v){const s=String(v||'item').toLowerCase().trim();if(['pound','pounds','lb','lbs'].includes(s))return'lbs';if(['ounce','ounces','oz'].includes(s))return'oz';if(['each','count','ct'].includes(s))return'each';return units.find(u=>u.toLowerCase()===s)||'item'}
function fillSelect(id,arr,current){$(id).innerHTML=options(arr,current)}function options(arr,current){return arr.map(v=>'<option '+(String(v).toLowerCase()===String(current||'').toLowerCase()?'selected':'')+'>'+esc(v)+'</option>').join('')}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
